spacetelescope/nirspec_pipe_testing_tool

- README.md
- calwebb_spec2_pytests/A_assign_wcs/test_assign_wcs.py
- calwebb_spec2_pytests/B_bkg_subtract/test_bkg_subtract.py
- calwebb_spec2_pytests/C_imprint_subtract/test_imprint_subtract.py
- calwebb_spec2_pytests/D_msa_flagging/test_msa_flagging.py
- calwebb_spec2_pytests/E_extract_2d/test_extract_2d.py
- calwebb_spec2_pytests/F_flat_field/test_flat_field.py
- calwebb_spec2_pytests/G_srctype/test_srctype.py
- calwebb_spec2_pytests/H_pathloss/test_pathloss.py
- calwebb_spec2_pytests/I_barshadow/test_barshadow.py
- calwebb_spec2_pytests/J_photom/test_photom.py
- calwebb_spec2_pytests/K_resample/test_resample.py
- calwebb_spec2_pytests/L_cube_build/test_cube_build.py
- calwebb_spec2_pytests/M_extract_1d/test_extract_1d.py
- calwebb_spec2_pytests/calwebb_spec2.cfg
- calwebb_spec2_pytests/core_utils.py
- calwebb_spec2_pytests/cwspec2_config.cfg
- utils/hdr_keywd_dict_sample.py
added time measuring routine. the background step is failing....
> Add bg and time pytests

- README.md
- calwebb_spec2_pytests/cwspec2_config.cfg
- utils/hdr_keywd_dict.py
- utils/hdr_keywd_dict_sample.py
- utils/run_cal_detector1.py
fixes for the ramp fit step to run and save the output file, and keywords for IFU data.
> Bug fixes after demo round4

- .gitignore
- README.md
- calwebb_spec2_pytests/A_assign_wcs/test_assign_wcs.py
- calwebb_spec2_pytests/B_bkg_subtract/test_bkg_subtract.py
- calwebb_spec2_pytests/C_imprint_subtract/test_imprint_subtract.py
- calwebb_spec2_pytests/D_msa_flagging/test_msa_flagging.py
- calwebb_spec2_pytests/E_extract_2d/test_extract_2d.py
- calwebb_spec2_pytests/F_flat_field/test_flat_field.py
- calwebb_spec2_pytests/G_srctype/srctype_utils.py
- calwebb_spec2_pytests/G_srctype/test_srctype.py
- calwebb_spec2_pytests/H_pathloss/test_pathloss.py
- calwebb_spec2_pytests/I_barshadow/test_barshadow.py
- calwebb_spec2_pytests/J_photom/test_photom.py
- calwebb_spec2_pytests/K_resample/test_resample.py
- calwebb_spec2_pytests/L_cube_build/test_cube_build.py
- calwebb_spec2_pytests/M_extract_1d/test_extract_1d.py
- calwebb_spec2_pytests/PTT_config.cfg
- calwebb_spec2_pytests/auxiliary_code/auxiliary_functions.py
- calwebb_spec2_pytests/auxiliary_code/compare_wcs_fs.py
- calwebb_spec2_pytests/auxiliary_code/compare_wcs_ifu.py
- calwebb_spec2_pytests/auxiliary_code/compare_wcs_mos.py
- calwebb_spec2_pytests/auxiliary_code/flattest_fs.py
- calwebb_spec2_pytests/auxiliary_code/flattest_ifu.py
- calwebb_spec2_pytests/auxiliary_code/flattest_mos.py
- calwebb_spec2_pytests/core_utils.py
- utils/run_cal_detector1.py
- Moved the instance to run steps to only occur when the step is running
- fixed function that checks for previous steps run up to that point
- fixed code on validation of assign_wcs and flat_field to not crash if slitlet is not projected on detector
- fixed name of section in config file that turns on and off the pipeline steps
> bug fixes, removing commented ref file pytests.

- README.md
- calwebb_spec2_pytests/PTT_config.cfg
- calwebb_spec2_pytests/auxiliary_code/compare_wcs_fs.py
- calwebb_spec2_pytests/auxiliary_code/compare_wcs_ifu.py
- calwebb_spec2_pytests/auxiliary_code/compare_wcs_mos.py
- calwebb_spec2_pytests/core_utils.py
- utils/data/calwebb_detector1.cfg
- utils/data/calwebb_tso1.cfg
- utils/hdr_keywd_check.py
- utils/hdr_keywd_dict_sample.py
- utils/level2b_hdr_keywd_check.py
- utils/level2b_hdr_keywd_dict_sample.py
- utils/run_cal_detector1.py
Fixed several bugs in various scripts.
> Fixes after name changes11

- calwebb_spec2_pytests/A_assign_wcs/test_assign_wcs.py
- calwebb_spec2_pytests/B_bkg_subtract/test_bkg_subtract.py
- calwebb_spec2_pytests/C_imprint_subtract/test_imprint_subtract.py
- calwebb_spec2_pytests/D_msa_flagging/test_msa_flagging.py
- calwebb_spec2_pytests/G_srctype/test_srctype.py
- calwebb_spec2_pytests/H_pathloss/test_pathloss.py
- calwebb_spec2_pytests/I_barshadow/test_barshadow.py
- calwebb_spec2_pytests/K_resample/test_resample.py
- calwebb_spec2_pytests/L_cube_build/test_cube_build.py
- calwebb_spec2_pytests/M_extract_1d/test_extract_1d.py
- calwebb_spec2_pytests/PTT_config.cfg
- calwebb_spec2_pytests/auxiliary_code/flattest_fs.py
- calwebb_spec2_pytests/calwebb_tso_spec2.cfg
- calwebb_spec2_pytests/core_utils.py
- utils/hdr_keywd_check.py
- utils/level2b_hdr_keywd_check.py
added configuration file for TSO calwebb_spec2 processing in full.
> bug fixes for BOTS data to run in PTT.

- utils/hdr_keywd_dict.py
SEQ_ID in the asdf schema should be a string.
> Fixing SEQ_ID to str

- calwebb_spec2_pytests/E_extract_2d/extract_2d_utils.py
- calwebb_spec2_pytests/E_extract_2d/test_extract_2d.py
- calwebb_spec2_pytests/PTT_config.cfg
- calwebb_spec2_pytests/auxiliary_code/compare_wcs_fs.py
- calwebb_spec2_pytests/auxiliary_code/compare_wcs_ifu.py
- calwebb_spec2_pytests/auxiliary_code/compare_wcs_mos.py
- calwebb_spec2_pytests/core_utils.py
- utils/level2b_hdr_keywd_dict_sample.py
@gkanarek I made some changes to the extract_2d validation tests and it now works fine.
I also added the final versions of the WCS scripts that James had sent around.
> Final wcs scripts

- .gitignore
- README.md
- calwebb_spec2_pytests/A_assign_wcs/test_assign_wcs.py
- calwebb_spec2_pytests/B_bkg_subtract/test_bkg_subtract.py
- calwebb_spec2_pytests/C_imprint_subtract/test_imprint_subtract.py
- calwebb_spec2_pytests/D_msa_flagging/test_msa_flagging.py
- calwebb_spec2_pytests/E_extract_2d/extract_2d_utils.py
- calwebb_spec2_pytests/E_extract_2d/test_extract_2d.py
- calwebb_spec2_pytests/F_flat_field/test_flat_field.py
- calwebb_spec2_pytests/G_srctype/test_srctype.py
- calwebb_spec2_pytests/H_pathloss/test_pathloss.py
- calwebb_spec2_pytests/I_barshadow/test_barshadow.py
- calwebb_spec2_pytests/J_photom/test_photom.py
- calwebb_spec2_pytests/K_resample/test_resample.py
- calwebb_spec2_pytests/L_cube_build/test_cube_build.py
- calwebb_spec2_pytests/M_extract_1d/test_extract_1d.py
- calwebb_spec2_pytests/PTT_config.cfg
- calwebb_spec2_pytests/auxiliary_code/auxiliary_functions.py
- calwebb_spec2_pytests/auxiliary_code/compare_wcs_fs.py
- calwebb_spec2_pytests/auxiliary_code/flattest_ifu.py
- calwebb_spec2_pytests/core_utils.py
- utils/prepare_data2run.py
- utils/run_cal_detector1.py
several changes to be able to run the pipeline on files from the 2 detectors in the same directory.
> Testing make header2

- calwebb_spec2_pytests/D_msa_flagging/test_msa_flagging.py
- calwebb_spec2_pytests/K_resample/test_resample.py
- calwebb_spec2_pytests/PTT_config.cfg
- calwebb_spec2_pytests/auxiliary_code/auxiliary_functions.py
- calwebb_spec2_pytests/auxiliary_code/compare_wcs_fs.py
- calwebb_spec2_pytests/auxiliary_code/compare_wcs_ifu.py
- calwebb_spec2_pytests/auxiliary_code/compare_wcs_mos.py
- calwebb_spec2_pytests/auxiliary_code/flattest_fs.py
- calwebb_spec2_pytests/auxiliary_code/flattest_ifu.py
- calwebb_spec2_pytests/auxiliary_code/flattest_mos.py
- utils/hdr_keywd_check.py
- utils/level2b_hdr_keywd_check.py
implemented residuals images for the flat field test and the logic for processing darks.
> Fixes after logging implementation take2

- calwebb_spec2_pytests/F_flat_field/test_flat_field.py
- calwebb_spec2_pytests/PTT_config.cfg
- calwebb_spec2_pytests/auxiliary_code/compare_wcs_fs.py
- calwebb_spec2_pytests/auxiliary_code/compare_wcs_ifu.py
- calwebb_spec2_pytests/auxiliary_code/compare_wcs_mos.py
- calwebb_spec2_pytests/auxiliary_code/flattest_fs.py
- calwebb_spec2_pytests/auxiliary_code/flattest_ifu.py
- calwebb_spec2_pytests/auxiliary_code/flattest_mos.py
- calwebb_spec2_pytests/calwebb_spec2.cfg
- calwebb_spec2_pytests/calwebb_tso_spec2.cfg
- calwebb_spec2_pytests/core_utils.py
- utils/hdr_keywd_check.py
- utils/hdr_keywd_dict.py
- utils/hdr_keywd_dict_sample.py
- utils/level2b_hdr_keywd_check.py
- utils/level2b_hdr_keywd_dict_sample.py
- utils/subarray_dict.py
fixed keyword dictionary and updated code for build 7.3 changes. Fixed subarray file to have correct start and end pixel values.
> fixes in prep for build 7.3 testing

- README.md
- utils/crm2STpipeline.py
- utils/hdr_keywd_dict.py
- utils/hdr_keywd_dict_sample.py
- utils/level2b_hdr_keywd_check.py
- utils/level2b_hdr_keywd_dict_sample.py
- utils/move_data2ext1.py
created "pipeline" script to convert CRM files into STScI pipeline ingestible files. Modified README file accordingly.
> Prep4build73

- calwebb_spec2_pytests/PTT_config.cfg
- utils/crm2STpipeline.py
- utils/prepare_data2run.py
added option to NOT change filter from opaque value at prepare data 2 run script, and modified script to convert ESA crm files for pipeline ingestion to include rotation for NRS1 and 2.
> Fixes4build73

- calwebb_spec2_pytests/PTT_config.cfg
- calwebb_spec2_pytests/auxiliary_code/auxiliary_functions.py
- calwebb_spec2_pytests/auxiliary_code/flattest_fs.py
- utils/ESAsim_erm2crm.py
- utils/ESAsim_post_processing.py
- utils/level2b_hdr_keywd_check.py
- utils/level2b_hdr_keywd_dict_sample.py
- utils/pthl_IPS_FS200A1.json
- utils/pthl_IPS_sim_FS.json
modified some keywords, fixed flattest script for build 7.3, and added ESA script to convert erm to crm
> changes to account for build 7.3

- README.md
- calwebb_spec2_pytests/A_assign_wcs/test_assign_wcs.py
- calwebb_spec2_pytests/E_extract_2d/extract_2d_utils.py
- calwebb_spec2_pytests/E_extract_2d/test_extract_2d.py
- calwebb_spec2_pytests/M_extract_1d/test_extract_1d.py
- calwebb_spec2_pytests/PTT_config.cfg
- calwebb_spec2_pytests/auxiliary_code/auxiliary_functions.py
- calwebb_spec2_pytests/auxiliary_code/flattest_mos.py
- calwebb_spec2_pytests/auxiliary_code/reffile_test.py
- calwebb_spec2_pytests/core_utils.py
- calwebb_spec2_pytests/run_PTT.py
- added ESA erm to crm conversion scripts.
- fixed several bugs 
- added master wrapper to run pytest and then move html report to given working directory in PTT config file.
> added bug fixes, ESA erm to crm scripts, master wrapper for PTT

- README.md
- calwebb_spec2_pytests/A_assign_wcs/test_assign_wcs.py
- calwebb_spec2_pytests/E_extract_2d/extract_2d_utils.py
- calwebb_spec2_pytests/F_flat_field/test_flat_field.py
- calwebb_spec2_pytests/H_pathloss/test_pathloss.py
- calwebb_spec2_pytests/I_barshadow/test_barshadow.py
- calwebb_spec2_pytests/M_extract_1d/test_extract_1d.py
- calwebb_spec2_pytests/PTT_config.cfg
- calwebb_spec2_pytests/auxiliary_code/auxiliary_functions.py
- calwebb_spec2_pytests/auxiliary_code/barshadow_testing.py
- calwebb_spec2_pytests/auxiliary_code/compare_wcs_fs.py
- calwebb_spec2_pytests/auxiliary_code/compare_wcs_ifu.py
- calwebb_spec2_pytests/auxiliary_code/compare_wcs_mos.py
- calwebb_spec2_pytests/auxiliary_code/create_metafile.py
- calwebb_spec2_pytests/auxiliary_code/flattest_fs.py
- calwebb_spec2_pytests/auxiliary_code/flattest_ifu.py
- calwebb_spec2_pytests/auxiliary_code/flattest_mos.py
- calwebb_spec2_pytests/auxiliary_code/reffile_test.py
- calwebb_spec2_pytests/calwebb_spec2.cfg
- calwebb_spec2_pytests/core_utils.py
- utils/hdr_keywd_check.py
Added:
- script to create/fix shutter configuration file
- barshadow test script
- modified PTT code to include the barshadow test
> Barshadow take5

- calwebb_spec2_pytests/auxiliary_code/barshadow_testing.py
bug fix for barshadow test script to pick up right column in reference file
> bug fix for barshadow test script

- calwebb_spec2_pytests/A_assign_wcs/test_assign_wcs.py
bug fixes to modify the EXP_TYPE keyword to the correct value according to the mode used.
> bug fix EXP_TYPE

- calwebb_spec2_pytests/E_extract_2d/extract_2d_utils.py
- calwebb_spec2_pytests/PTT_config.cfg
- calwebb_spec2_pytests/auxiliary_code/compare_wcs_fs.py
- calwebb_spec2_pytests/auxiliary_code/compare_wcs_ifu.py
- calwebb_spec2_pytests/auxiliary_code/compare_wcs_mos.py
- calwebb_spec2_pytests/auxiliary_code/flattest_fs.py
- calwebb_spec2_pytests/auxiliary_code/flattest_ifu.py
- calwebb_spec2_pytests/auxiliary_code/flattest_mos.py
- utils/crm2STpipeline.py
- utils/hdr_keywd_check.py
- utils/level2b_hdr_keywd_check.py
- utils/level2b_hdr_keywd_dict_map2sim.py
- utils/level2b_hdr_keywd_dict_sample.py
added script to match IPS keyword values to pipeline and modified other scripts to run without errors for build 7.4
> implementation of script to match IPS keywords to pipeline

- calwebb_spec2_pytests/A_assign_wcs/test_assign_wcs.py
- calwebb_spec2_pytests/E_extract_2d/test_extract_2d.py
- calwebb_spec2_pytests/K_resample/test_resample.py
- calwebb_spec2_pytests/M_extract_1d/test_extract_1d.py
- calwebb_spec2_pytests/PTT_config.cfg
- calwebb_spec2_pytests/auxiliary_code/create_metafile.py
- calwebb_spec2_pytests/calwebb_tso-spec2.cfg
- utils/run_cal_detector1.py
modified configuration file to run and save the source type step products.
> bug fixes in general

- README.md
- calwebb_spec2_pytests/PTT_config.cfg
- utils/fix_pointing.py
- utils/prepare_data2run.py
added script to fix poining in count rate file, and made little bug fixes
> implemented fix_pointing.py

- utils/hdr_keywd_dict.py
- utils/hdr_keywd_dict_sample.py
- utils/level2b_hdr_keywd_dict_map2sim.py
- utils/level2b_hdr_keywd_dict_sample.py
added a possible value for DATAMODEL keyword for calwebb_detector1 and reformatted dictionaries
> Fixes after fixpointing take2

- calwebb_spec2_pytests/A_assign_wcs/test_assign_wcs.py
- calwebb_spec2_pytests/B_bkg_subtract/test_bkg_subtract.py
- calwebb_spec2_pytests/C_imprint_subtract/test_imprint_subtract.py
- calwebb_spec2_pytests/D_msa_flagging/test_msa_flagging.py
- calwebb_spec2_pytests/E_extract_2d/test_extract_2d.py
- calwebb_spec2_pytests/F_flat_field/test_flat_field.py
- calwebb_spec2_pytests/G_srctype/test_srctype.py
- calwebb_spec2_pytests/H_pathloss/test_pathloss.py
- calwebb_spec2_pytests/I_barshadow/test_barshadow.py
- calwebb_spec2_pytests/J_photom/test_photom.py
- calwebb_spec2_pytests/K_resample/test_resample.py
- calwebb_spec2_pytests/L_cube_build/test_cube_build.py
- calwebb_spec2_pytests/M_extract_1d/test_extract_1d.py
- calwebb_spec2_pytests/PTT_config.cfg
- calwebb_spec2_pytests/auxiliary_code/compare_wcs_fs.py
- calwebb_spec2_pytests/auxiliary_code/compare_wcs_ifu.py
- calwebb_spec2_pytests/auxiliary_code/flattest_fs.py
- calwebb_spec2_pytests/auxiliary_code/flattest_ifu.py
- calwebb_spec2_pytests/auxiliary_code/flattest_mos.py
- calwebb_spec2_pytests/conftest.py
- calwebb_spec2_pytests/core_utils.py
- calwebb_spec2_pytests/run_PTT.py
- utils/crm2STpipeline.py
- utils/hdr_keywd_check.py
- utils/level2b_hdr_keywd_check.py
- utils/level2b_hdr_keywd_dict_map2sim.py
- utils/mk_pttconfig_file.py
- utils/prepare_data2run.py
- utils/run_cal_detector1.py
- changed working_directory for output_directory
- format fixes in many scripts
- added a new script to create a PTT configuration file
> several modifications

- README.md
corrected bugs and made numbers and notes bold for clarity
> corrected instructions

- nirspec_pipe_testing_tool/calwebb_spec2_pytests/A_assign_wcs/test_assign_wcs.py
- nirspec_pipe_testing_tool/calwebb_spec2_pytests/auxiliary_code/auxiliary_functions.py
- nirspec_pipe_testing_tool/calwebb_spec2_pytests/auxiliary_code/compare_wcs_fs.py
- nirspec_pipe_testing_tool/calwebb_spec2_pytests/auxiliary_code/compare_wcs_ifu.py
- nirspec_pipe_testing_tool/calwebb_spec2_pytests/auxiliary_code/compare_wcs_mos.py
made minor modifications to be able to run the testing code with a datamodel instead of a file
> assign wcs test with datamodel instead of file

- nirspec_pipe_testing_tool/utils/dict_info/hdr_keywd_dict_sample.py
- nirspec_pipe_testing_tool/utils/dict_info/level2b_hdr_keywd_dict_sample.py
- nirspec_pipe_testing_tool/utils/hdr_keywd_check.py
commented out line to force OBS-DATE keyword to be later than 2016
> commented OBS-DATE to force to be something

- nirspec_pipe_testing_tool/calwebb_spec3_pytests/A_master_background/test_master_background.py
- nirspec_pipe_testing_tool/utils/data/terminal_commands_calwebb_spec3_steps.txt
removed some pausing commands and included text file with commands for running spec3
> added text file with commands for running spec3 from terminal

- nirspec_pipe_testing_tool/calwebb_spec2_pytests/B_bkg_subtract/test_bkg_subtract.py
- nirspec_pipe_testing_tool/calwebb_spec2_pytests/C_imprint_subtract/imprint_subtract_utils.py
- nirspec_pipe_testing_tool/calwebb_spec2_pytests/C_imprint_subtract/test_imprint_subtract.py
- nirspec_pipe_testing_tool/calwebb_spec2_pytests/G_srctype/srctype_utils.py
- nirspec_pipe_testing_tool/calwebb_spec2_pytests/G_srctype/test_srctype.py
- nirspec_pipe_testing_tool/calwebb_spec2_pytests/I_barshadow/test_barshadow.py
- nirspec_pipe_testing_tool/calwebb_spec2_pytests/J_photom/photom_utils.py
- nirspec_pipe_testing_tool/calwebb_spec2_pytests/J_photom/test_photom.py
- nirspec_pipe_testing_tool/calwebb_spec2_pytests/M_extract_1d/test_extract_1d.py
- nirspec_pipe_testing_tool/calwebb_spec3_pytests/A_master_background/master_background_utils.py
- nirspec_pipe_testing_tool/calwebb_spec3_pytests/A_master_background/test_master_background.py
- nirspec_pipe_testing_tool/utils/data/PTT_config_example.cfg
- nirspec_pipe_testing_tool/utils/mk_pttconfig_file.py
implemented numerical test for background subtract, logic for source type (according to user input from APT), changed threshold for pathloss, and added test units used for photom step
> implemented sanity checks for build 7.5

- README.md
- nirspec_pipe_testing_tool/calwebb_spec2_pytests/A_assign_wcs/test_assign_wcs.py
- nirspec_pipe_testing_tool/calwebb_spec2_pytests/B_bkg_subtract/test_bkg_subtract.py
- nirspec_pipe_testing_tool/calwebb_spec2_pytests/C_imprint_subtract/test_imprint_subtract.py
- nirspec_pipe_testing_tool/calwebb_spec2_pytests/D_msa_flagging/test_msa_flagging.py
- nirspec_pipe_testing_tool/calwebb_spec2_pytests/E_extract_2d/test_extract_2d.py
- nirspec_pipe_testing_tool/calwebb_spec2_pytests/F_flat_field/test_flat_field.py
- nirspec_pipe_testing_tool/calwebb_spec2_pytests/G_srctype/test_srctype.py
- nirspec_pipe_testing_tool/calwebb_spec2_pytests/H_pathloss/test_pathloss.py
- nirspec_pipe_testing_tool/calwebb_spec2_pytests/I_barshadow/test_barshadow.py
- nirspec_pipe_testing_tool/calwebb_spec2_pytests/J_photom/test_photom.py
- nirspec_pipe_testing_tool/calwebb_spec2_pytests/K_resample/test_resample.py
- nirspec_pipe_testing_tool/calwebb_spec2_pytests/L_cube_build/test_cube_build.py
- nirspec_pipe_testing_tool/calwebb_spec2_pytests/M_extract_1d/extract_1d_utils.py
- nirspec_pipe_testing_tool/calwebb_spec2_pytests/M_extract_1d/test_extract_1d.py
- nirspec_pipe_testing_tool/calwebb_spec2_pytests/auxiliary_code/auxiliary_functions.py
- nirspec_pipe_testing_tool/calwebb_spec3_pytests/A_master_background/master_background_utils.py
- nirspec_pipe_testing_tool/calwebb_spec3_pytests/A_master_background/test_master_background.py
- nirspec_pipe_testing_tool/calwebb_spec3_pytests/B_exp_to_source/exp_to_source_utils.py
- nirspec_pipe_testing_tool/calwebb_spec3_pytests/B_exp_to_source/test_exp_to_source.py
- nirspec_pipe_testing_tool/utils/__init__.py
- nirspec_pipe_testing_tool/utils/data/PTT_config_example.cfg
- nirspec_pipe_testing_tool/utils/data/terminal_commands_calwebb_spec3_steps.txt
- nirspec_pipe_testing_tool/utils/mk_multiprocessing_cfg.py
- nirspec_pipe_testing_tool/utils/run_PTT.py
- nirspec_pipe_testing_tool/utils/run_PTT_with_multiprocess.py
- multiprocessing was implemented
- added structure for future development of spec3 but stopped developing as there are too many unknowns at the moment
things that still need to be implemented:
- switches for completion, validation, and reference file tests
- detailed code to run step by step the spec3 pipeline
- should differentiate between spec2 code (checks) and spec3, maybe e.g. s3_resample?
> Implement multiprocessing with given number of cores

- README.md
- nirspec_pipe_testing_tool/calwebb_spec2_pytests/A_assign_wcs/assign_wcs_utils.py
- nirspec_pipe_testing_tool/calwebb_spec2_pytests/A_assign_wcs/test_assign_wcs.py
- nirspec_pipe_testing_tool/calwebb_spec2_pytests/M_extract_1d/test_extract_1d.py
- nirspec_pipe_testing_tool/calwebb_spec2_pytests/auxiliary_code/auxiliary_functions.py
- nirspec_pipe_testing_tool/calwebb_spec2_pytests/auxiliary_code/barshadow_testing.py
- nirspec_pipe_testing_tool/calwebb_spec2_pytests/auxiliary_code/compare_wcs_fs.py
- nirspec_pipe_testing_tool/calwebb_spec2_pytests/auxiliary_code/compare_wcs_ifu.py
- nirspec_pipe_testing_tool/calwebb_spec2_pytests/auxiliary_code/compare_wcs_mos.py
- nirspec_pipe_testing_tool/calwebb_spec2_pytests/auxiliary_code/flattest_fs.py
- nirspec_pipe_testing_tool/calwebb_spec2_pytests/auxiliary_code/flattest_ifu.py
- nirspec_pipe_testing_tool/calwebb_spec2_pytests/auxiliary_code/flattest_mos.py
- nirspec_pipe_testing_tool/calwebb_spec2_pytests/auxiliary_code/pathloss_fs_ps.py
- nirspec_pipe_testing_tool/calwebb_spec2_pytests/auxiliary_code/pathloss_fs_ps_S400A1.py
- nirspec_pipe_testing_tool/calwebb_spec2_pytests/auxiliary_code/pathloss_fs_uni.py
- nirspec_pipe_testing_tool/calwebb_spec2_pytests/auxiliary_code/pathloss_ifu_ps.py
- nirspec_pipe_testing_tool/calwebb_spec2_pytests/auxiliary_code/pathloss_ifu_uni.py
- nirspec_pipe_testing_tool/calwebb_spec2_pytests/auxiliary_code/pathloss_mos_ps.py
- nirspec_pipe_testing_tool/calwebb_spec2_pytests/auxiliary_code/pathloss_mos_uni.py
- nirspec_pipe_testing_tool/utils/change_filter_opaque2science.py
- nirspec_pipe_testing_tool/utils/hdr_keywd_check.py
- nirspec_pipe_testing_tool/utils/level2b_hdr_keywd_check.py
- nirspec_pipe_testing_tool/utils/mk_multiprocessing_cfg.py
- nirspec_pipe_testing_tool/utils/mk_pttconfig_file.py
- nirspec_pipe_testing_tool/utils/run_PTT.py
- nirspec_pipe_testing_tool/utils/run_PTT_with_multiprocess.py
- nirspec_pipe_testing_tool/utils/run_cal_detector1.py
- modified the multiprocessing script to be able to run cal_det1 in multiprocessing option
> allow multiple PTT.cfg files in one dir and run caldet1 in multiprocessing

- README.md
- nirspec_pipe_testing_tool/calwebb_spec2_pytests/A_assign_wcs/test_assign_wcs.py
- nirspec_pipe_testing_tool/calwebb_spec2_pytests/D_msa_flagging/test_msa_flagging.py
- nirspec_pipe_testing_tool/calwebb_spec2_pytests/M_extract_1d/test_extract_1d.py
- nirspec_pipe_testing_tool/calwebb_spec2_pytests/auxiliary_code/__init__.py
- nirspec_pipe_testing_tool/calwebb_spec2_pytests/auxiliary_code/barshadow_testing.py
- nirspec_pipe_testing_tool/calwebb_spec2_pytests/auxiliary_code/create_metafile.py
- nirspec_pipe_testing_tool/calwebb_spec2_pytests/auxiliary_code/flattest_fs.py
- nirspec_pipe_testing_tool/calwebb_spec2_pytests/auxiliary_code/flattest_ifu.py
- nirspec_pipe_testing_tool/calwebb_spec2_pytests/auxiliary_code/flattest_mos.py
- nirspec_pipe_testing_tool/calwebb_spec2_pytests/auxiliary_code/msa_flagging_testing.py
- nirspec_pipe_testing_tool/core_utils.py
- nirspec_pipe_testing_tool/utils/change_keywd.py
- nirspec_pipe_testing_tool/utils/data/PTT_config_example.cfg
- nirspec_pipe_testing_tool/utils/data/calwebb_dark.cfg
- nirspec_pipe_testing_tool/utils/data/terminal_commands_calwebb_detector1_steps.txt
- nirspec_pipe_testing_tool/utils/dict_info/hdr_keywd_dict.py
- nirspec_pipe_testing_tool/utils/dict_info/hdr_keywd_dict_sample.py
- nirspec_pipe_testing_tool/utils/dict_info/level2b_hdr_keywd_dict_sample.py
- nirspec_pipe_testing_tool/utils/hdr_keywd_check.py
- nirspec_pipe_testing_tool/utils/level2b_hdr_keywd_check.py
- nirspec_pipe_testing_tool/utils/mk_multiprocessing_cfg.py
- nirspec_pipe_testing_tool/utils/mk_pttconfig_file.py
modified:   README.md - updated version of latest tag
modified:   nirspec_pipe_testing_tool/calwebb_spec2_pytests/A_assign_wcs/test_assign_wcs.py - Added check to see if running spec2 is appropriate according to EXP_TYPE rules taken from CRDS
modified:   nirspec_pipe_testing_tool/calwebb_spec2_pytests/D_msa_flagging/test_msa_flagging.py - added validation
modified:   nirspec_pipe_testing_tool/calwebb_spec2_pytests/M_extract_1d/test_extract_1d.py - bug fix
modified:   nirspec_pipe_testing_tool/calwebb_spec2_pytests/auxiliary_code/__init__.py - added msa flagging test
modified:   nirspec_pipe_testing_tool/calwebb_spec2_pytests/auxiliary_code/barshadow_testing.py  - bug fix
modified:   nirspec_pipe_testing_tool/calwebb_spec2_pytests/auxiliary_code/create_metafile.py  - bug fix
modified: …
> implemented msa_flagging testing and modified code accordingly.

- nirspec_pipe_testing_tool/utils/level2b_hdr_keywd_check.py
and added a non-crashing exit for non-covered modes
> added fix to allow for MOS_sim mode in level2b_hdr_keywd check

- README.md
- nirspec_pipe_testing_tool/calwebb_spec2_pytests/A_assign_wcs/test_assign_wcs.py
- nirspec_pipe_testing_tool/calwebb_spec2_pytests/E_extract_2d/test_extract_2d.py
- nirspec_pipe_testing_tool/calwebb_spec2_pytests/G_srctype/test_srctype.py
- nirspec_pipe_testing_tool/calwebb_spec2_pytests/auxiliary_code/barshadow_testing.py
- nirspec_pipe_testing_tool/calwebb_spec2_pytests/auxiliary_code/flattest_mos.py
- nirspec_pipe_testing_tool/calwebb_spec2_pytests/auxiliary_code/msa_flagging_testing.py
- nirspec_pipe_testing_tool/calwebb_spec3_pytests/A_master_background/test_master_background.py
- nirspec_pipe_testing_tool/utils/hdr_keywd_check.py
- nirspec_pipe_testing_tool/utils/level2b_hdr_keywd_check.py
- nirspec_pipe_testing_tool/utils/mk_pttconfig_file.py
- nirspec_pipe_testing_tool/utils/run_PTT_with_multiprocess.py
- nirspec_pipe_testing_tool/utils/run_cal_detector1.py
- implemented the change of the d-flat and the f-flat =1 for the MOS flat field test in order to solve the discrepancy with the pipeline.
- fixed a few bugs found long the way in other scripts
> Modifications mos flattest

- nirspec_pipe_testing_tool/calwebb_spec2_pytests/I_barshadow/test_barshadow.py
- nirspec_pipe_testing_tool/calwebb_spec2_pytests/auxiliary_code/barshadow_testing.py
- nirspec_pipe_testing_tool/utils/dict_info/hdr_keywd_dict.py
- nirspec_pipe_testing_tool/utils/dict_info/hdr_keywd_dict_sample.py
- nirspec_pipe_testing_tool/utils/dict_info/level2b_hdr_keywd_dict_sample.py
changed the dictionaries to include the source type keyword and the barshadow code to accept datamodels as input
> barshadow changes

- README.md
- nirspec_pipe_testing_tool/calwebb_spec2_pytests/A_assign_wcs/test_assign_wcs.py
- nirspec_pipe_testing_tool/calwebb_spec2_pytests/auxiliary_code/auxiliary_functions.py
- nirspec_pipe_testing_tool/calwebb_spec2_pytests/auxiliary_code/flattest_mos.py
- nirspec_pipe_testing_tool/core_utils.py
- nirspec_pipe_testing_tool/utils/hdr_keywd_check.py
- nirspec_pipe_testing_tool/utils/level2b_hdr_keywd_check.py
- nirspec_pipe_testing_tool/utils/mk_pttconfig_file.py
- nirspec_pipe_testing_tool/utils/run_cal_detector1.py
fixed issue with flat field testing for the MOS case, along with many other bugs. A new tag will be created at this point.
> fixed flattest_mos and some other bugs

- README.md
- nirspec_pipe_testing_tool/calwebb_spec2_pytests/D_msa_flagging/test_msa_flagging.py
- nirspec_pipe_testing_tool/calwebb_spec2_pytests/I_barshadow/test_barshadow.py
- nirspec_pipe_testing_tool/calwebb_spec2_pytests/auxiliary_code/auxiliary_functions.py
- nirspec_pipe_testing_tool/calwebb_spec2_pytests/auxiliary_code/barshadow_testing.py
- nirspec_pipe_testing_tool/calwebb_spec2_pytests/auxiliary_code/flattest_fs.py
- nirspec_pipe_testing_tool/calwebb_spec2_pytests/auxiliary_code/flattest_ifu.py
- nirspec_pipe_testing_tool/calwebb_spec2_pytests/auxiliary_code/flattest_mos.py
- nirspec_pipe_testing_tool/calwebb_spec2_pytests/auxiliary_code/msa_flagging_testing.py
- nirspec_pipe_testing_tool/calwebb_spec2_pytests/auxiliary_code/pathloss_fs_ps.py
- nirspec_pipe_testing_tool/calwebb_spec2_pytests/auxiliary_code/pathloss_fs_uni.py
- nirspec_pipe_testing_tool/calwebb_spec2_pytests/auxiliary_code/pathloss_ifu_ps.py
- nirspec_pipe_testing_tool/calwebb_spec2_pytests/auxiliary_code/pathloss_ifu_uni.py
- nirspec_pipe_testing_tool/calwebb_spec2_pytests/auxiliary_code/pathloss_mos_ps.py
- nirspec_pipe_testing_tool/calwebb_spec2_pytests/auxiliary_code/pathloss_mos_uni.py
- nirspec_pipe_testing_tool/core_utils.py
- nirspec_pipe_testing_tool/utils/crm2STpipeline.py
- nirspec_pipe_testing_tool/utils/level2b_hdr_keywd_check.py
- nirspec_pipe_testing_tool/utils/level2b_hdr_keywd_dict_map2sim.py
- nirspec_pipe_testing_tool/utils/mk_multiprocessing_cfg.py
- nirspec_pipe_testing_tool/utils/mk_pttconfig_file.py
- nirspec_pipe_testing_tool/utils/move_data2ext1.py
- nirspec_pipe_testing_tool/utils/run_cal_detector1.py
added several close() statements throughout to improve memory management and other minor stuff for the validation notebooks
> Changes4notebooks

- README.md
- nirspec_pipe_testing_tool/calwebb_spec2_pytests/auxiliary_code/flattest_mos.py
- nirspec_pipe_testing_tool/utils/hdr_keywd_check.py
added shutter config name in header and modified mos ffield test to not crash with objects instead of file names
> fixed ffield test to work with objs

- README.md
- nirspec_pipe_testing_tool/calwebb_spec2_pytests/K_photom/photom_utils.py
- nirspec_pipe_testing_tool/calwebb_spec2_pytests/auxiliary_code/msa_flagging_testing.py
- nirspec_pipe_testing_tool/utils/change_keywd.py
- nirspec_pipe_testing_tool/utils/fix_pointing.py
- fix/added documentation to fix pointing and change keyword scripts
- minimize bug in extract_1d by setting aper_angle=45.0 for non-MOS data
> aper_angle to 45.0 for non-MOS data

- README.md
- nirspec_pipe_testing_tool/calwebb_spec2_pytests/auxiliary_code/flattest_fs.py
- nirspec_pipe_testing_tool/calwebb_spec2_pytests/auxiliary_code/flattest_ifu.py
- nirspec_pipe_testing_tool/calwebb_spec2_pytests/auxiliary_code/flattest_mos.py
- nirspec_pipe_testing_tool/utils/run_cal_detector1.py
also fixed issue with file header being modified again after cal_detector1
> fixed ffield notebooks crashing with spec2 output

- README.md
- nirspec_pipe_testing_tool/calwebb_spec2_pytests/auxiliary_code/compare_wcs_fs.py
- nirspec_pipe_testing_tool/utils/run_cal_detector1.py
fixed issue with truth file for assign_wcs testing when not comparing to ESA
> fixed failing test when not comparing to ESA file

- README.md
- nirspec_pipe_testing_tool/calwebb_spec2_pytests/I_pathloss/test_pathloss.py
- nirspec_pipe_testing_tool/calwebb_spec2_pytests/J_barshadow/test_barshadow.py
- nirspec_pipe_testing_tool/calwebb_spec2_pytests/auxiliary_code/auxiliary_functions.py
- nirspec_pipe_testing_tool/calwebb_spec2_pytests/auxiliary_code/barshadow_testing.py
- nirspec_pipe_testing_tool/calwebb_spec2_pytests/auxiliary_code/check_corners_extract2d.py
- nirspec_pipe_testing_tool/calwebb_spec2_pytests/auxiliary_code/compare_wcs_fs.py
- nirspec_pipe_testing_tool/calwebb_spec2_pytests/auxiliary_code/compare_wcs_ifu.py
- nirspec_pipe_testing_tool/calwebb_spec2_pytests/auxiliary_code/compare_wcs_mos.py
- nirspec_pipe_testing_tool/calwebb_spec2_pytests/auxiliary_code/flattest_fs.py
- nirspec_pipe_testing_tool/calwebb_spec2_pytests/auxiliary_code/flattest_ifu.py
- nirspec_pipe_testing_tool/calwebb_spec2_pytests/auxiliary_code/flattest_mos.py
- nirspec_pipe_testing_tool/calwebb_spec2_pytests/auxiliary_code/msa_flagging_testing.py
- nirspec_pipe_testing_tool/calwebb_spec2_pytests/auxiliary_code/pathloss_fs_ps.py
- nirspec_pipe_testing_tool/calwebb_spec2_pytests/auxiliary_code/pathloss_fs_uni.py
- nirspec_pipe_testing_tool/calwebb_spec2_pytests/auxiliary_code/pathloss_ifu_ps.py
- nirspec_pipe_testing_tool/calwebb_spec2_pytests/auxiliary_code/pathloss_ifu_uni.py
- nirspec_pipe_testing_tool/calwebb_spec2_pytests/auxiliary_code/pathloss_mos.py
- nirspec_pipe_testing_tool/utils/change_keywd.py
- nirspec_pipe_testing_tool/utils/run_tool.py
this includes a bunch of small bug fixes that prevent crashing. Will create tag 3.0.1 after this merge.
Problems still that remain are:
- flat_field plots seem to be saved strangely after the first slit figure 
- flat field results do not agree with pipeline with latest set of reference files (though previous do work fine for the same CV3 test data)
> bug fixes all over to improve code

- nirspec_pipe_testing_tool/calwebb_spec2_pytests/auxiliary_code/auxiliary_functions.py
- nirspec_pipe_testing_tool/calwebb_spec2_pytests/auxiliary_code/barshadow_testing.py
- nirspec_pipe_testing_tool/calwebb_spec2_pytests/auxiliary_code/compare_wcs_fs.py
- nirspec_pipe_testing_tool/calwebb_spec2_pytests/auxiliary_code/compare_wcs_ifu.py
- nirspec_pipe_testing_tool/calwebb_spec2_pytests/auxiliary_code/compare_wcs_mos.py
- nirspec_pipe_testing_tool/calwebb_spec2_pytests/auxiliary_code/flattest_fs.py
- nirspec_pipe_testing_tool/calwebb_spec2_pytests/auxiliary_code/flattest_ifu.py
- nirspec_pipe_testing_tool/calwebb_spec2_pytests/auxiliary_code/flattest_mos.py
- nirspec_pipe_testing_tool/calwebb_spec2_pytests/auxiliary_code/msa_flagging_testing.py
- nirspec_pipe_testing_tool/calwebb_spec2_pytests/auxiliary_code/pathloss_mos.py
- nirspec_pipe_testing_tool/core_utils.py
- nirspec_pipe_testing_tool/utils/level2b_hdr_keywd_check.py
Clean up a large number of issues causing test failures with the current pipeline.
> Test cleanup
